### ISSUE TITLE
Pkg.add("FFTW") fails in Windows Julia 1.0.3

### ISSUE THREAD

**Issue by mattcbro** [JuliaMath/FFTW.jl#84]
It can't download something and fails.  All my package adds are terribly slow on Windows.  It's pretty much unusable.
```
julia> Pkg.add("FFTW")
 Resolving package versions...
 Installed AbstractFFTs ─ v0.3.2
 Installed FFTW ───────── v0.2.4
  Updating `C:\Users\matt\.julia\environments\v1.0\Project.toml`
  [7a1cc6ca] + FFTW v0.2.4
  Updating `C:\Users\matt\.julia\environments\v1.0\Manifest.toml`
  [621f4979] + AbstractFFTs v0.3.2
  [7a1cc6ca] + FFTW v0.2.4
  Building FFTW → `C:\Users\matt\.julia\packages\FFTW\p7sLQ\deps\build.log`
┌ Error: Error building `FFTW`:
│ ┌ Warning: On Windows, creating file symlinks requires Administrator privileges
│ └ @ Base.Filesystem file.jl:789
│ ┌ Warning: platform_key() is deprecated, use platform_key_abi() from now on
│ │   caller = ip:0x0
│ └ @ Core :-1
│ ┌ Warning: Could not extract the platform key of https://github.com/JuliaMath/FFTWBuilder/releases/download/v3.3.8+1/FFTW.x86_64-w64-mingw32.tar.gz; continuing...
│ └ @ BinaryProvider C:\Users\matt\.julia\packages\BinaryProvider\4F5Hq\src\Prefix.jl:185
│ [ Info: Downloading https://github.com/JuliaMath/FFTWBuilder/releases/download/v3.3.8+1/FFTW.x86_64-w64-mingw32.tar.gz to C:\Users\matt\.julia\packages\FFTW\p7sLQ\deps\usr\downloads\FFTW.x86_64-w64-mingw32.tar.gz...
│ ERROR: LoadError: LoadError: Could not download https://github.com/JuliaMath/FFTWBuilder/releases/download/v3.3.8+1/FFTW.x86_64-w64-mingw32.tar.gz to C:\Users\matt\.julia\packages\FFTW\p7sLQ\deps\usr\downloads\FFTW.x86_64-w64-mingw32.tar.gz:
│ ErrorException("")
│ Stacktrace:
│  [1] error(::String) at .\error.jl:33
│  [2] #download#93(::Bool, ::Function, ::String, ::String) at C:\Users\matt\.julia\packages\BinaryProvider\4F5Hq\src\PlatformEngines.jl:498
│  [3] #download at .\none:0 [inlined]
│  [4] #download_verify#94(::Bool, ::Bool, ::Bool, ::Function, ::String, ::String, ::String) at C:\Users\matt\.julia\packages\BinaryProvider\4F5Hq\src\PlatformEngines.jl:567
│  [5] #download_verify at .\none:0 [inlined]
│  [6] #install#133(::Prefix, ::String, ::Bool, ::Bool, ::Bool, ::Function, ::String, ::String) at C:\Users\matt\.julia\packages\BinaryProvider\4F5Hq\src\Prefix.jl:314
│  [7] (::getfield(BinaryProvider, Symbol("#kw##install")))(::NamedTuple{(:prefix, :force, :verbose),Tuple{Prefix,Bool,Bool}}, ::typeof(install), ::String, ::String) at .\none:0
│  [8] top-level scope at C:\Users\matt\.julia\packages\FFTW\p7sLQ\deps\build_fftw.jl:37
│  [9] include at .\boot.jl:317 [inlined]
│  [10] include_relative(::Module, ::String) at .\loading.jl:1044
│  [11] include(::Module, ::String) at .\sysimg.jl:29
│  [12] include(::String) at .\client.jl:392
│  [13] top-level scope at C:\Users\matt\.julia\packages\FFTW\p7sLQ\deps\build.jl:48
│  [14] include at .\boot.jl:317 [inlined]
│  [15] include_relative(::Module, ::String) at .\loading.jl:1044
│  [16] include(::Module, ::String) at .\sysimg.jl:29
│  [17] include(::String) at .\client.jl:392
│  [18] top-level scope at none:0
│ in expression starting at C:\Users\matt\.julia\packages\FFTW\p7sLQ\deps\build_fftw.jl:33
│ in expression starting at C:\Users\matt\.julia\packages\FFTW\p7sLQ\deps\build.jl:19
│ Exception calling "DownloadFile" with "2" argument(s): "The operation has timed out."
│ At line:5 char:1
│ + $webclient.DownloadFile("https://github.com/JuliaMath/FFTWBuilder/rel ...
│ + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
│     + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
│     + FullyQualifiedErrorId : WebException
│
└ @ Pkg.Operations C:\cygwin\home\Administrator\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.0\Pkg\src\Operations.jl:1097
```

**Comment by ararslan** [comment]
@staticfloat, is there something we need to be doing differently here with our BinaryProvider setup?

**Comment by mattcbro** [comment]
I exited Julia,  restarted it and then issued a Pkg.build("FFTW") command and that actually worked.  Not sure what's going on with the slow package times.  I thought that was fixed come version 1.0.   It probably means the problem is not reproducible.  Sorry.

**Comment by staticfloat** [comment]
@ararslan other than having built this with an old version of BinaryBuilder (so there is no version number embedded within the tarball name) no I think this looks fine.

**Comment by ararslan** [comment]
Okay, thanks for checking, @staticfloat. I'll close this issue for now since it seems to have solved itself, but @mattcbro, please reopen if it happens again.

**Comment by neveritt** [comment]
I'm on Julia 1.2 in Windows and I seem to be experiencing something that to me look very similar to what mattcbro was experiencing. However, restarting Julia and triggering a Pkg.build("FFTW) did not solve my issue. @ararslan, should I open a separate issue?

julia> Pkg.build("FFTW")
  Building Conda → `C:\Users\Niklas Everitt\.julia\packages\Conda\kLXeC\deps\build.log`
  Building FFTW ─→ `C:\Users\Niklas Everitt\.julia\packages\FFTW\2okGQ\deps\build.log`
┌ Error: Error building `FFTW`:
│ ┌ Warning: On Windows, creating file symlinks requires Administrator privileges
│ └ @ Base.Filesystem file.jl:797
│ ┌ Warning: platform_key() is deprecated, use platform_key_abi() from now on
│ │   caller = ip:0x0
│ └ @ Core :-1
│ ┌ Warning: Could not extract the platform key of https://github.com/JuliaMath/FFTWBuilder/releases/download/v3.3.8+1/FFTW.x86_64-w64-mingw32.tar.gz; continuing...
│ └ @ BinaryProvider C:\Users\Niklas Everitt\.julia\packages\BinaryProvider\TcAwt\src\Prefix.jl:185
│ [ Info: Downloading https://github.com/JuliaMath/FFTWBuilder/releases/download/v3.3.8+1/FFTW.x86_64-w64-mingw32.tar.gz to C:\Users\Niklas Everitt\.julia\packages\FFTW\2okGQ\deps\usr\downloads\FFTW.x86_64-w64-mingw32.tar.gz...
│ ERROR: LoadError: LoadError: Could not download https://github.com/JuliaMath/FFTWBuilder/releases/download/v3.3.8+1/FFTW.x86_64-w64-mingw32.tar.gz to C:\Users\Niklas Everitt\.julia\packages\FFTW\2okGQ\deps\usr\downloads\FFTW.x86_64-w64-mingw32.tar.gz:
│ ErrorException("")
│ Stacktrace:
│  [1] error(::String) at .\error.jl:33
│  [2] #download#93(::Bool, ::typeof(BinaryProvider.download), ::String, ::String) at C:\Users\Niklas Everitt\.julia\packages\BinaryProvider\TcAwt\src\PlatformEngines.jl:498
│  [3] #download at .\none:0 [inlined]
│  [4] #download_verify#94(::Bool, ::Bool, ::Bool, ::typeof(download_verify), ::String, ::String, ::String) at C:\Users\Niklas Everitt\.julia\packages\BinaryProvider\TcAwt\src\PlatformEngines.jl:567
│  [5] #download_verify at .\tuple.jl:0 [inlined]
│  [6] #install#133(::Prefix, ::String, ::Bool, ::Bool, ::Bool, ::typeof(install), ::String, ::String) at C:\Users\Niklas Everitt\.julia\packages\BinaryProvider\TcAwt\src\Prefix.jl:314
│  [7] (::getfield(BinaryProvider, Symbol("#kw##install")))(::NamedTuple{(:prefix, :force, :verbose),Tuple{Prefix,Bool,Bool}}, ::typeof(install), ::String, ::String) at .\tuple.jl:0
│  [8] top-level scope at C:\Users\Niklas Everitt\.julia\packages\FFTW\2okGQ\deps\build_fftw.jl:37
│  [9] include at .\boot.jl:328 [inlined]
│  [10] include_relative(::Module, ::String) at .\loading.jl:1094
│  [11] include(::Module, ::String) at .\Base.jl:31
│  [12] include(::String) at .\client.jl:431
│  [13] top-level scope at C:\Users\Niklas Everitt\.julia\packages\FFTW\2okGQ\deps\build.jl:49
│  [14] include at .\boot.jl:328 [inlined]
│  [15] include_relative(::Module, ::String) at .\loading.jl:1094
│  [16] include(::Module, ::String) at .\Base.jl:31
│  [17] include(::String) at .\client.jl:431
│  [18] top-level scope at none:5
│ in expression starting at C:\Users\Niklas Everitt\.julia\packages\FFTW\2okGQ\deps\build_fftw.jl:33
│ in expression starting at C:\Users\Niklas Everitt\.julia\packages\FFTW\2okGQ\deps\build.jl:20
│ caused by [exception 2]
│ 
│ Stacktrace:
│  [1] error() at .\error.jl:42
│  [2] #download#93(::Bool, ::typeof(BinaryProvider.download), ::String, ::String) at C:\Users\Niklas Everitt\.julia\packages\BinaryProvider\TcAwt\src\PlatformEngines.jl:492
│  [3] #download at .\none:0 [inlined]
│  [4] #download_verify#94(::Bool, ::Bool, ::Bool, ::typeof(download_verify), ::String, ::String, ::String) at C:\Users\Niklas Everitt\.julia\packages\BinaryProvider\TcAwt\src\PlatformEngines.jl:567
│  [5] #download_verify at .\tuple.jl:0 [inlined]
│  [6] #install#133(::Prefix, ::String, ::Bool, ::Bool, ::Bool, ::typeof(install), ::String, ::String) at C:\Users\Niklas Everitt\.julia\packages\BinaryProvider\TcAwt\src\Prefix.jl:314
│  [7] (::getfield(BinaryProvider, Symbol("#kw##install")))(::NamedTuple{(:prefix, :force, :verbose),Tuple{Prefix,Bool,Bool}}, ::typeof(install), ::String, ::String) at .\tuple.jl:0
│  [8] top-level scope at C:\Users\Niklas Everitt\.julia\packages\FFTW\2okGQ\deps\build_fftw.jl:37
│  [9] include at .\boot.jl:328 [inlined]
│  [10] include_relative(::Module, ::String) at .\loading.jl:1094
│  [11] include(::Module, ::String) at .\Base.jl:31
│  [12] include(::String) at .\client.jl:431
│  [13] top-level scope at C:\Users\Niklas Everitt\.julia\packages\FFTW\2okGQ\deps\build.jl:49
│  [14] include at .\boot.jl:328 [inlined]
│  [15] include_relative(::Module, ::String) at .\loading.jl:1094
│  [16] include(::Module, ::String) at .\Base.jl:31
│  [17] include(::String) at .\client.jl:431
│  [18] top-level scope at none:5
│ caused by [exception 1]
│ IOError: symlink: operation not permitted (EPERM)
│ Stacktrace:
│  [1] uv_error at .\libuv.jl:90 [inlined]
│  [2] symlink(::String, ::String) at .\file.jl:800
│  [3] probe_symlink_creation(::String) at C:\Users\Niklas Everitt\.julia\packages\BinaryProvider\TcAwt\src\PlatformEngines.jl:121
│  [4] #probe_platform_engines!#30(::Bool, ::typeof(BinaryProvider.probe_platform_engines!)) at C:\Users\Niklas Everitt\.julia\packages\BinaryProvider\TcAwt\src\PlatformEngines.jl:175
│  [5] probe_platform_engines! at C:\Users\Niklas Everitt\.julia\packages\BinaryProvider\TcAwt\src\PlatformEngines.jl:169 [inlined]
│  [6] __init__() at C:\Users\Niklas Everitt\.julia\packages\BinaryProvider\TcAwt\src\BinaryProvider.jl:28
│  [7] _include_from_serialized(::String, ::Array{Any,1}) at .\loading.jl:685
│  [8] _require_search_from_serialized(::Base.PkgId, ::String) at .\loading.jl:765
│  [9] _require(::Base.PkgId) at .\loading.jl:990
│  [10] require(::Base.PkgId) at .\loading.jl:911
│  [11] require(::Module, ::Symbol) at .\loading.jl:906
│  [12] include at .\boot.jl:328 [inlined]
│  [13] include_relative(::Module, ::String) at .\loading.jl:1094
│  [14] include(::Module, ::String) at .\Base.jl:31
│  [15] include(::String) at .\client.jl:431
│  [16] top-level scope at C:\Users\Niklas Everitt\.julia\packages\FFTW\2okGQ\deps\build.jl:49
│  [17] include at .\boot.jl:328 [inlined]
│  [18] include_relative(::Module, ::String) at .\loading.jl:1094
│  [19] include(::Module, ::String) at .\Base.jl:31
│  [20] include(::String) at .\client.jl:431
│  [21] top-level scope at none:5
│ Exception setting "SecurityProtocol": "Cannot convert null to type "System.Net.SecurityProtocolType" due to invalid enumeration values. Specify one of the following enumeration values and try ag
│ ain. The possible enumeration values are "Ssl3, Tls"."
│ At line:1 char:35
│ + [System.Net.ServicePointManager]:: <<<< SecurityProtocol =
│     + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
│     + FullyQualifiedErrorId : PropertyAssignmentException
│ 
│ Exception calling "DownloadFile" with "2" argument(s): "The underlying connection was closed: An unexpected error occurred on a send."
│ At line:5 char:24
│ + $webclient.DownloadFile <<<< ("https://github.com/JuliaMath/FFTWBuilder/releases/download/v3.3.8+1/FFTW.x86_64-w64-mingw32.tar.gz", "C:\Users\Niklas Everitt\.julia\packages\FFTW\2okGQ\deps\usr
│ \downloads\FFTW.x86_64-w64-mingw32.tar.gz")
│     + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
│     + FullyQualifiedErrorId : DotNetMethodException
│ 
└ @ Pkg.Operations C:\cygwin\home\Administrator\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.2\Pkg\src\backwards_compatible_isolation.jl:647
false

**Comment by stevengj** [comment]
This `On Windows, creating file symlinks requires Administrator privileges` seems to appear in a lot of Julia packages if you google that message.

@staticfloat in https://github.com/bicycle1885/CodecZlib.jl/issues/24#issuecomment-412472390 said that this is fixed by the latest version of BinaryBuilder.  So, it should be fixed the next time we upload new FFTW binary packages.  For example, it should be fixed by #105 (which is currently stalled by a Windows build failure).

In the meantime, a workaround is apparently to [enable Developer Mode](https://github.com/JuliaPlots/Makie.jl/issues/154#issuecomment-426138434) in Windows so that you can create symlinks?   (Or it might be a problem with your home directory being on a network drive where you can't create symlinks?)

**Comment by neveritt** [comment]
@stevengj, thanks for the quick reply.

The developer mode workaround seemed to work.

**Comment by stevengj** [comment]
Should be fixed now that #105 is merged.
